AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  SearchWorker:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.6
      Handler: SearchWorker.lambda_handler
      CodeUri:
        Bucket: postcore-bucket
        Key:
          Fn::Sub: Postcore.SearchApi/SearchWorker.zip
      MemorySize: 128
      Timeout: 3
      Role: arn:aws:iam::489967615225:role/lambda-basic-execution-role
      Events:
        PostcoreApiSns:
          Type: SNS
          Properties:
            Topic: arn:aws:sns:us-west-2:489967615225:postcore-api
  SearchApi:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.6
      Handler: SearchApi.lambda_handler
      CodeUri:
        Bucket: postcore-bucket
        Key:
          Fn::Sub: Postcore.SearchApi/SearchApi.zip
      MemorySize: 128
      Timeout: 3
      Role: arn:aws:iam::489967615225:role/lambda-basic-execution-role
      Events:
        PostcoreSearchApi:
          Type: Api
          Properties:
            Path: /{q}
            Method: get
